### ISSUE TITLE
Starting conversion refreshes to "new post" page. No progress/conversion at all.

### ISSUE THREAD

**Issue by alicam** [Automattic/newspack-content-converter#24]
**Describe the conversion bug**

I've got something like 17,000 (!) posts awaiting conversion. When I click to start the conversion, I'm expecting to see some sort of screen with a progress meter? But instead I see a new (standard) post edit screen with the URL:

https://my-domain-here/wp-admin/post-new.php?newspack-content-converter

Of course, that's not what I'm supposed to see. 

I have checked the DB table created, and nothing's happening.

**Source of the error**
No idea what's causing it.

**Expected behavior**
I would have expected the conversion to start and a progress screen to display.

**Screenshots**
None. The screen I see is the "new post edit" screen with no messages.

**Comment by alicam** [comment]
Note this error as the conversion attempts to start. The error is in client-slde JS, as best I can tell.

(Also a service worker script fails to register as it is not called via https.)

![image](https://user-images.githubusercontent.com/44537/69893982-0eddc780-136d-11ea-8c99-94baea602c0f.png)

Any help? @iuravic ?

**Comment by akkiverma** [comment]
+1
Facing exactly same issue.

**Comment by iuravic** [comment]
Hi @alicam. Thanks for reaching out and reporting this!

Firstly, please note that this plugin is currently made to serve as a developer's tool, not yet fully polished for use by an end user, which means that the UI is not fully complete; as an example of this, no progress meter is implemented, but a spinning "loader GIF" informs the user of ongoing conversion, as well as a more detailed Console output.

Having said that, the plugin is supposed to do a decent job!, and we've already used it to convert hundreds of thousands of posts, and is being improved frequently.

I will soon update the README with info about the main functionality, usage, and future plans.

Let's try and see together why this error is occurring. Firstly, please make sure that you're using:
- the very latest WP version (currently 5.3),
- this plugin's latest release (tagged as 0.0.4-alpha).

When updating the Plugin, it's important to manually Deactivate and then Delete it, and only then install the new version, and finally to Activate it. This is required for proper installation/deinstallation actions performed in background during such Deletion and Activation.

Once you've updated the WP and the Plugin, do try again and please let me know of the outcome.

I'm noting your note about the error occurring at
```
document.getElementsByClassName("edit-post-layout__content")[0].style.display="none"
```
Thanks for being so detailed. Can you please provide the rest of the Console output, too?
I am hopeful that updating to a new version of WP should remove this error, but if not, I am already prepared to push an update resolving this, since I suspect to know the solution if it will be needed.

**Comment by iuravic** [comment]
@akkiverma, are you getting the exact same console output, or a different kind of message in the Console?

**Comment by akkiverma** [comment]
I did't tried the console, no idea how to do it. But other than that, it is redirecting to adding new post page happened with me too. Then I came back to the run converter page, which showed it is in progress but I didn't saw any progress gif, I left the page opened for a very long period but nothing happened.

**Comment by akkiverma** [comment]
I deleted, downloaded and installed the latest 0.0.4-alpha plugin from releases and after installing, inside WordPress dashboard, the plugin version shows as Version 0.0.1-alpha

so could it be possible if latest release doesn't have the latest version attachment?

**Comment by iuravic** [comment]
> the plugin version shows as Version 0.0.1-alpha

@akkiverma, if you were using the latest Release, then this is OK even, if it shows the older tag in the list of plugins.

> I did't tried the console, no idea how to do it. But other than that, it is redirecting to adding new post page happened with me too.

Would it be possible for you to get a screenshot of the New Post page to which the plugin redirects after you clicked Convert? And also after taking the screenshot, if you are using Chrome or FireFox, please right click your mouse anywhere in the page and select "Inspect', then click the "Console" tab, and copt-paste here the output you get there. But, to do all this meaningfully for debugging purposes, first please Delete the plugin, and install and Activate it once again (the real "retry conversion" functionality has not yet been implemented, so that's why it needs to be reinstalled at this point).

**Comment by akkiverma** [comment]
As required I deleted the plugin, upload, installed and open the Run Conversion page. Here's the console output of that:

```
WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
v @ ?v=2.0:6
D @ ?v=2.0:6
o @ ?v=2.0:6
```

Console output when I click the Conversion Button

```
Uncaught TypeError: Cannot read property 'style' of undefined
    at window.onload (main.js?ver=1575404541:1)
window.onload @ main.js?ver=1575404541:1
load (async)
(anonymous) @ main.js?ver=1575404541:1
n 			@ main.js?ver=1575404541:1
(anonymous) @ main.js?ver=1575404541:1
(anonymous) @ main.js?ver=1575404541:1

WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
v @ ?v=2.0:6
D @ ?v=2.0:6
o @ ?v=2.0:6
```

and it redirects me to page - 

`https://my-domain-here/wp-admin/post-new.php?newspack-content-converter`

Here's the screenshot of that:

![add new](https://user-images.githubusercontent.com/20245997/70087749-e7bc1a00-163a-11ea-90d5-401451b02a9a.png)

After coming back to the conversion page, page contents are:

![Run Conversion](https://user-images.githubusercontent.com/20245997/70087773-f0aceb80-163a-11ea-806f-e8e032728cc4.png)

and console output is:

```
?v=2.0:6 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
v @ ?v=2.0:6
D @ ?v=2.0:6
o @ ?v=2.0:6
```

**Comment by akkiverma** [comment]
Now even if I leave the conversion tab open for hours, nothing would happen.  But I also see that there are 409 records in the ncc_wp_posts table. So yes, the conversion is happening but I won't know when it finishes and what to do next after conversion?

**Comment by alicam** [comment]
@iuravic Thanks for looking into this.

Now running .0.0.4-alpha tagged release and no difference.

I get the same console error as @akkiverma regarding the undefined DOM element (as shown above/earlier).

I also get a failed serviceworker message. Not sure it's related. Happy to get you on a zoom conf call if you need to look closer. Just don't want to paste too much here in public.

A

**Comment by alicam** [comment]
@iuravic Noticed one more thing.

Immediately before the page reloads, after clicking the "Run Conversion" button, this is shown in the console:

![image](https://user-images.githubusercontent.com/44537/70088931-531de000-166b-11ea-8d5d-768e51b84a06.png)

A 'queued' message is sent, but then it breaks in heartbeat.min.js (and I've not worked out if that's a problem for your plugin or not!).

A

**Comment by akkiverma** [comment]
I am able to see 725 records in the ncc_wp_posts table. So for 702 posts and other pages, seems like the conversion is complete. Now should I run the  Re-apply Patchers?

Whenever I am opening an old post, it still shows the classic editor inside the gutenberg editor, means the non-blocks contents.

![234234324](https://user-images.githubusercontent.com/20245997/70089678-a9c0f500-163e-11ea-8912-c2cb9f737991.png)

What should I do next?

**Comment by akkiverma** [comment]
Some posts after conversions still have image floating out of the column size. Is patching them would fix  this issue?

**Comment by alicam** [comment]
@iuravic Any further thoughts on my bugs/errors here? I really need to get this thing done.

**Comment by iuravic** [comment]
Created a PR https://github.com/Automattic/newspack-content-converter/pull/26 which should fix the one issue we pinpointed https://github.com/Automattic/newspack-content-converter/issues/24#issuecomment-559902750.

As soon as it's merged, I'll create a new release.

---

@alicam Thanks for your feedback.

---

@akkiverma :

> Now even if I leave the conversion tab open for hours, nothing would happen. But I also see that there are 409 records in the ncc_wp_posts table. So yes, the conversion is happening but I won't know when it finishes and what to do next after conversion has run in full.

The rows exist in the table don't signify that the conversion was performed -- these records are inserted during the Plugin installation; the column `post_conten_gutenberg_converted` shows whether they've been converted -- if it's empty, it means they weren't.

> and it redirects me to page - https://my-domain-here/wp-admin/post-new.php?newspack-content-converter

Yes, that's fine, this is the expected redirection. Once we clear out the issue, an app will load on top of this page which currently looks like this -- note that this is very a much DEV version of the UI:

![image](https://user-images.githubusercontent.com/29167323/70326003-b490ab00-1833-11ea-805e-e96bfa664411.png)

> Now should I run the Re-apply Patchers?

No, you'll want to use Run Conversion only, once the app loads properly.

**Comment by akkiverma** [comment]
Thanks for replying. 

In what case scenario do we need to use Patch Content?

Is there any need to deactivate plugins before starting conversion like Ad-inserter, Yoast, YARPP etc which injects content inside posts?

**Comment by iuravic** [comment]
@akkiverma for now let's first see if the new Release will fix your current issue.

A README will soon be published with more details, but for now you shouldn't need to Re-apply Patchers in a regular case.

As far as other plugins go, you should consider what kind of an effect the other plugins have on a post's/page's content, and the fact that this plugin does the following: takes a post's/page's HTML source, converts it to Gutenberg blocks source, and updates the post/page. It is very probable that you shouldn't need to disable those.

Once the conversion is done, you can Deactivate and completely Delete the plugin. If your data is sensitive, you might want to back up the database before conversion, or even reference the `ncc_wp_posts` table (the custom table created and used by this plugin, which holds the backup of the original post source) bvut also note that this table gets completely dropped once you remove the plugin.

**Comment by akkiverma** [comment]
Thank you, that's quiet helpful.

**Comment by iuravic** [comment]
Hi @akkiverma and @alicam , a new Release was published which I'm hoping would fix the issue you're experiencing -- https://github.com/Automattic/newspack-content-converter/releases/tag/0.0.5-alpha Following are the instructions on how to use it.

Please bear in mind as I've already explained this is an early version of the Plugin, with a very unpolished UI (it currently serves well as a developer's tool, but is not yet packaged into a solid end product). We're currently working on the new features and an UI which will raise it to the next level. So for now, please be a bit patient and follow these steps:
- first Deactivate and completely Delete the current version of the plugin (make sure to backup your important data/content safely, if you need to),
- install the 0.0.5-alpha release, and Activate it,
- delete your browser's cache, if there is a need for that on your Site,
- in the next step, you only get to Start Conversion once -- there is currently no "Retry Conversion" feature, so make sure you are able to keep the Plugin's browser tab open for the required time until conversion is fully complete,
- in WP-admin, click on the Newspack Content Converter > Run Conversion > then click the big blue button "Start Conversion Now".

If the new Release was successful in detecting and clearing the matter you were experiencing, you should still be redirected to the page `/wp-admin/post-new.php?newspack-content-converter`, and on top of that page the Converter App should now get loaded, with a spinning gif image, informing you of the ongoing conversion (if you wish, you may carefully open the Console which outputs a more detailed progress). Make sure not to close this tab until conversion is completely finished, because as I mentioned, there's currently no way to restart the conversion, and you'd need to repeat the whole procedure in that case. We'll be providing these features soon and making the Plugin more comfortable for use.

Another thing to note, if after you've clicked the big blue button "Start Conversion Now", you would again go to the Newspack Content Converter > Run Conversion, on that page you'd only see a message informing you that the conversion is currently in progress -- in the other active tab, but this page itself doesn't perform conversion. This might be a bit confusing, so that's why I'm pointing it out.

**Comment by akkiverma** [comment]
Thank you very much for this explanation in detail. Gonna try it shortly.

**Comment by akkiverma** [comment]
Hi, I tried the plugin, it worked in exact same manner as you explained above. Although I did have to deactivate Yoast SEO premium plugin before as when it is activated, the plugin was not able to fetch details of posts. 

For safer side, I activated other content plugins too like ad-injector, related posts, YARPP etc. 

Now after fully running conversion, in the first run, although it said conversion complete, most of the posts got missed from conversion. Plugin in the console showed that it converted those posts but in actual it didn't happen. Then I ran it again, and this time only few posts it missed.

I checked the posts randomly for testing. It also converted the homepage to HTML which broke the layout of the home. So I have to build that again. Not complaining but sharing the feedback.

I didn't run the converter 3rd for remaining posts as those were short articles and didn't felt the need to do so again. 

Here's some errors, console was showing when I started the conversion plus these same appears again the page reload to start next batch:

```
main.js?ver=1575832717:1 Not found element by class name edit-post-layout__content
[Violation] 'setInterval' handler took 110ms
main.js?ver=1575832717:1 converting 3266, 2/100 
2main.js?ver=1575832717:1 Not found element by class name edit-post-layout__content
[Violation] 'setInterval' handler took 171ms
main.js?ver=1575832717:1 Not found element by class name edit-post-layout__content
main.js?ver=1575832717:1 converting 3273, 3/100 
2main.js?ver=1575832717:1 Not found element by class name edit-post-layout__content
main.js?ver=1575832717:1 converting 3284, 4/100 
7[Violation] 'setTimeout' handler took <N>ms
2main.js?ver=1575832717:1 Not found element by class name edit-post-layout__content
main.js?ver=1575832717:1 converting 3291, 5/100 
main.js?ver=1575832717:1 Final error: Not found element by class name edit-post-layout__content
main.js?ver=1575832717:1 converting 3300, 6/100 
main.js?ver=1575832717:1 converting 3326, 7/100 
```

**Comment by iuravic** [comment]
> I did have to deactivate Yoast SEO premium plugin before as when it is activated, the plugin was not able to fetch details of posts

Thanks so much for sharing experience with these.
Als thank you for the Console output which is quite useful.

If I understood correctly, re-running the conversion did the trick on the failed ones. At this moment, we're planning on adding a feature "Retry Unsuccessful Conversions", so in the future we'd have this option covered. It's also quite possible that the Plugin would automatically retry failed ones upon finishing the whole Conversion.

Seeing how we've solved the issue of the Plugin failing to load and run for you, I'm closing the issue.

Thanks @akkiverma and @alicam for reporting and helping improve the quality!
