### ISSUE TITLE
Image Blocks Invalid After Conversion

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-content-converter#8]
**Describe the conversion bug**
It appears that all image blocks generate Gutenberg Block validation errors when viewed in the editor. This looks to be because the `<img />` tags have height and width attributes which are not present in the saved output of the Image block. Sample block validation error here:

**Source of the error**
Sample block validation error observed in https://thelensnola-newspack.mystagingwebsite.com/wp-admin/post.php?post=126136&action=edit: 

```
Block validation: Block validation failed for `core/image` (Object).

Content generated by `save` function:

<div class="wp-block-image wp-caption alignleft"><figure class="alignleft"><img src="https://thelensnola.org/wp-content/uploads/2019/04/SmithFawer_Image_MikeFawer-copy.jpg" alt="" class="wp-image-126149"/><figcaption>Defense attorney Mike Fawer: a storied legal career</figcaption></figure></div>

Content retrieved from post body:

<div class="wp-block-image wp-caption alignleft"><figure class="alignleft"><img src="https://thelensnola.org/wp-content/uploads/2019/04/SmithFawer_Image_MikeFawer-copy.jpg" alt="" class="wp-image-126149" height="412" width="325"/><figcaption>Defense attorney Mike Fawer: a storied legal career</figcaption></figure></div>
```

**Expected behavior**
Converted image blocks are valid and editable in editor.

**Comment by laurelfulford** [comment]
I think another possible cause is where the aligned left, right and center classes are being added. The markup around the image blocks looks like this in the converted content:

```
<div class="wp-block-image wp-caption alignleft">
<figure class="alignleft">
...
</figure>
</div>
```

... when it should look like:

```
<div class="wp-block-image">
<figure class="alignleft size-large is-resized">
...
</figure>
</div>
```

The image block is odd because it does this -- it moves some of the align classes (`alignleft` `alignright` `aligncenter`) to an element that doesn't have the `.wp-block-*` class, which is an unusual pattern.

(It looks like the `.wp-caption` class also isn't used on image blocks you create in the editor; not sure this would be causing issues, though). 

This is also causing visual issues in the theme -- it's applying a 50% width to the `alignleft` and `alignright` classes; since they're nested, you end up with an image taking up half the space available to it. We can update the styles to hide this for the short term -- just give me a ping if we should do that!
